remote_theme: pmarsceill/just-the-docs

aux_links:
  "resource-x on GitHub":
    - "//github.com/khalidx/resource-x"

footer_content: "Copyright &copy; 2019-2020 Khalid Zoabi. Distributed with an <a href=\"https://github.com/khalidx/resource-x/tree/master/LICENSE\">MIT license</a>."
